# Generated by Django 4.0.2 on 2022-02-25 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dendrites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dendID', models.CharField(max_length=20)),
                ('dendPic', models.BinaryField()),
                ('prod_name', models.CharField(max_length=50)),
                ('prod_category', models.CharField(max_length=50)),
                ('mfg_date', models.CharField(max_length=20)),
                ('exp_date', models.CharField(max_length=20)),
            ],
        ),
    ]
