# Generated by Django 4.0.2 on 2022-03-11 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('densecID', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dendrites',
            name='prod_disc',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
